Feat/#143 email certification
TeamPiickle/client pull request #147
Opened 2022-08-21 15:20 UTC by NaveOWO

- [ ] 브랜치명, 브랜치 알맞게 설정
- [ ] Reviewer, Assignees, Label, Milestone, Issue(PR 작성 후에) 붙이기
- [ ] PR이 승인된 경우 해당 브랜치는 삭제하기

## 📌 내용

- 

<br />

## 📌 내가 알게 된 부분

- 

<br />

## 📌 질문할 부분 

- 

<br />

## 📸 스크린샷

<img src="" width=80% />

2022-08-22 16:27 UTC, joohaem requested changes
> onclick 함수 이름 정할 때, clickHandle 이라는 말을 넣어주는게 좋을까요..?! 예를 들어서 <인증메일 재전송>버튼이면 resendBtnClickHadle은 너무 길어서 그냥 resendEmail 같이 이름 지어버렸는데 함수의 이벤트 이름을 넣어주는게 더 직관적이라는 지적도 들어서욤

컨벤션 나름이지 않을까 하는데, 저는 handleClick~ 이런식으로 짓곤합니다,,
props 로 넘겨받는 네이밍이 아니라면, resendEmail 라는 함수명 형식도 좋다고 생각해요!
다만 resendEmail 은 그 자체로 의미 해석이 되는데, 그게 좀 어렵다면 더 서술하는 방향으로!!

---
> (그래서 말인데.. Join 에 index.tsx 파일은 필요가 없는거 맞죠..?! 맞는 것 같은데 혹시 아닌가..? 해서 지우진 못했어욤....)

필요없어 보이는 거 마음껏 지워주세요 ^`3` 잘못됐다면 후에 수정하면 되니까!

---
> usenavigate 드디어 써보네요 행-복
페이지마다 props 다르게 주는 공통 컴포넌트 직접 만들어보니깐 갓벽이해
router도 폴더 여기저기 왓다리갔다리 하면서 어떻게 export해놓고 그런거.. 다 알았습니다
정규표현식 처음 써봐욤!

하놔 제가 다 뿌듯하네요!!!!!!!!! 너무 고생많으셨어요👍‼🔥🔥🔥🔥
피클 작업하면서 더더 많이 함께 성장했으면 합니다 !!!

---
아래 제가 생각하는 바들 코멘트 가감없이 달았어요,
모두 받아들이지 않으셔도 되고,
더 공부해보시면서 함께 의논하는 시간 가지면 좋을 것 같습니다\

2022-08-22 16:27 UTC, joohaem commented on src/components/JoinPage/ EmailAuthentication/index.tsx
> +  };
🚨반영 필요🚨

input 의 onChange 마다 setState 를 시킨다면, ref 를 사용하는 의미가 있을까요?
ref 를 사용하는 의의는
uncontrolled input 과 controlled input 중에서 uncontrolled input 을 사용하기 위해서입니다!
onChange 마다 state를 변경시키는 것은 controlled input 의 의미구요

인풋에 텍스트를 타이핑 할 떄마다가 아닌, 제출할 시에만 인푸스이 내용을 판단하면 되지 않을까요?

2022-08-22 16:27 UTC, joohaem commented on src/components/JoinPage/ EmailAuthentication/index.tsx
> +    const email: string | null = emailInput.current && emailInput.current.value;
null 타입을 옵셔널로 정의하는 이유는 무엇인가요?

2022-08-22 16:27 UTC, joohaem commented on src/components/JoinPage/ EmailAuthentication/index.tsx
> +    const regEmail = /^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*\.[a-zA-Z]{2,3}$/;
GoooooD👀👀👀

2022-08-22 16:27 UTC, joohaem commented on src/components/JoinPage/EmailConfirm/index.tsx
> +    </St.EmailConfirmContainer>
👀수정 제안👀

여기에서도 가독성을 위해 `EmailConfirm` 단어를 제거함이 어떨까 합니다

2022-08-22 16:27 UTC, joohaem commented on src/components/JoinPage/EmailConfirm/style.ts
> +    width: 100%;
🚨수정 필요🚨

width: 100% 속성은 디폴트 값으로, 제거하셔도 좋을 것 같습니다

2022-08-22 16:27 UTC, joohaem commented on src/Router.tsx
> +        <Route path={routePaths.EmailConfirm} element={PublicRoute({ Component: <EmailConfirmPage /> })} />
🚨수정 필요🚨

둘 다 로그인 시에 접근하면 안 되는 페이지로,
아래와 같이 restriced 인자를 넘겨주어야 합니다

```suggestion
        <Route
          path={routePaths.EmailAuthentication}
          element={PublicRoute({ Component: <EmailAuthenticationPage />, restricted: true })}
        />
        <Route path={routePaths.EmailConfirm} element={PublicRoute({ Component: <EmailConfirmPage />, restricted: true })} />
```

---
혹은, 같은 회원가입 카테고리의 페이지인데
sub routing 하심이 어떨까 합니다
`join/authentication` , `join/confirm` 이런 식으루요!!

2022-08-22 16:27 UTC, joohaem commented on src/components/JoinPage/common/PageProgressBar/style.ts
> +    width: ${({ rate }) => rate}rem;
👀수정 제안👀

해당 width 값은 디바이스의 크기에 따라 달라질 상대적 길이일 것 같은데,
rem 값보다는 % 상대 길이로 표현하심이 어떨까합니다!

2022-08-22 16:27 UTC, joohaem commented on src/components/JoinPage/ EmailAuthentication/index.tsx
> +      });
이 state 로 넘겨주는 데이터가 불안정하다는 문제를, sub routing 으로 해결할 수 있지 않을까 합니다!

2022-08-22 16:27 UTC, joohaem commented on src/components/JoinPage/EmailConfirm/index.tsx
> +  const userEmail = state.userEmail;
```suggestion
  const { state: { useEmail } } = useLocation();
```

이런 식으로 줄일 수 있지 않을까 합니다! (+ 타입단언)

2022-08-22 16:27 UTC, joohaem commented on src/components/JoinPage/EmailConfirm/index.tsx
> +  return (
재전송 버튼을 누르면 이메일부터 다시 쳐야하는 flow 가 맞나요??!

2022-08-22 16:27 UTC, joohaem commented on src/components/JoinPage/Header/index.tsx
> +}
WoW👀👀👍

2022-08-22 16:27 UTC, joohaem commented on src/components/JoinPage/EmailConfirm/style.ts
> +    //프로토타입 없음
🚨공통 컴포넌트 만들어 주세요!!!!!!!!!!!!!!!🚨

2022-08-24 14:18 UTC, NYeonK reviewed
언니야 너무 멋있다!!!!!!!😆😎
props 주는 거 잘하도라👀👍 하다가 모를 때 언니가 올린 거 참고했자나><
수고했으야~!~!!~!~!!!!!!!

2022-08-24 14:18 UTC, NYeonK commented on src/components/JoinPage/ EmailAuthentication/style.ts
> +    width: 1.7rme;
rme 오타나써요~!

2022-08-24 14:18 UTC, NYeonK commented on src/components/JoinPage/ EmailAuthentication/style.ts
> +    /* justify-content: space-between; */
필요한 주석인지 궁금합니다😋

2022-08-25 12:01 UTC, NaveOWO commented on src/Router.tsx
> +        <Route path={routePaths.Join} element={PublicRoute({ Component: <JoinPage /> })} />
우앗 그렇군용! `restricted` 배워가욤 코드 다시 봐볼께요!

2022-08-25 12:03 UTC, NaveOWO commented on src/components/JoinPage/ EmailAuthentication/index.tsx
> +    </St.EmailAuthenticationSection>
나는 무조건 컴포넌트명을 명시해줘야하는줄 알았어!😭 너무 중복돼서 나도 정신사나웠는데 우쒸 지적해줘서 너무 고마워요!!!👍

2022-08-25 12:03 UTC, NaveOWO commented on src/components/MainPage/MoodPiickle/index.tsx
> +              <St.CategoryContent className={`GTM_${moodPiickle.title.slice(0, 4)}`}>
넵 알겠슴미다앙~

2022-08-25 12:04 UTC, NaveOWO commented on src/components/JoinPage/ErrorPopup/style.ts
> +    width: 100%;
우앗 저는 불필요해보여도 혹시몰라서(?) 항상 width값을 지정해줬는데, 불필요한건 안쓰는게 맞군요!! 감사해용🌟

2022-08-25 12:04 UTC, NaveOWO commented on src/components/JoinPage/ErrorPopup/index.tsx
> +export default function ErrorPopup(props: any) {
미쳤나보네

2022-08-25 12:04 UTC, NaveOWO commented on src/components/JoinPage/ EmailAuthentication/index.tsx
> +  const [isEmailInValid, setIsEmailInValid] = useState<any>(false);
싹들켰네..ㅋㅋ 이 컴포넌트 삭제할께요! 헤헤😭

2022-08-25 12:07 UTC, NaveOWO commented on src/components/JoinPage/ErrorPopup/index.tsx
> +  const { isPopupOpen, setIsPopupOpen } = props;
삭제될 컴포넌트이긴 하지만, 배워갈께요 감사해요!!😭
`setState 함수를 직접 props 로 넘겨주면, 상위의 state 값의 변경을 추적하기 어려워집니다` -->  이유는 state값을 변경을 알기위해서 컴포넌트를 여러개 확인해야하기 때문일까요..?

2022-08-25 12:07 UTC, NaveOWO commented on src/components/JoinPage/ErrorPopup/index.tsx
> +  };
네에에!

2022-08-25 12:08 UTC, NaveOWO commented on src/components/JoinPage/ EmailAuthentication/index.tsx
> +  };
그러게요..! useref를 사용했으면서 왜 onchange를 했지..? 바로 수정 갈겨서 업데이트 할께요!! 감사해요🌟

2022-08-25 12:14 UTC, NaveOWO commented on src/components/JoinPage/ EmailAuthentication/index.tsx
> +    const email: string | null = emailInput.current && emailInput.current.value;
email이 null값이라고 뜰 때도 있어서 그랬던 것 같아요! 그래서 다음 코드에 if문에도 email값이 없을때를 가정해줬었는데, 아마 onchange로 email을 받아와서 그런 것 같아요! 위에 로직 고치면서 수정할께요😁

2022-08-25 12:15 UTC, NaveOWO commented on src/components/JoinPage/EmailConfirm/index.tsx
> +    </St.EmailConfirmContainer>
대찬성🔥🔥

2022-08-25 12:15 UTC, NaveOWO commented on src/components/JoinPage/EmailConfirm/style.ts
> +    width: 100%;
넵!!

2022-08-25 12:27 UTC, NaveOWO commented on src/Router.tsx
> +        <Route path={routePaths.EmailConfirm} element={PublicRoute({ Component: <EmailConfirmPage /> })} />
엄...!! 코드가 섞였는데, 첫번째 오빠가 리뷰달아준 router.tsx 에 Join 페이지를 지우고, 위와같이 Join 폴더 안에 각 페이지들을 라우팅해준거였어요! 이렇게 되면 sub routing을 할 수 없는거 맞나요?

2022-08-25 12:28 UTC, NaveOWO commented on src/components/JoinPage/common/PageProgressBar/style.ts
> +    width: ${({ rate }) => rate}rem;
엥 그러네 왜 %로 안했지!? 감사해욤😁😁🥺

2022-08-25 12:33 UTC, NaveOWO commented on src/components/JoinPage/ EmailAuthentication/index.tsx
> +      });
state로 넘겨주는 데이터가 불안정하다는 문제가 정확히 어떤건지 잘 모르겠어요🥺 emailText 가 null값일 수도 있다는 의미일까요??

2022-08-25 12:37 UTC, NaveOWO commented on src/components/JoinPage/EmailConfirm/index.tsx
> +  const userEmail = state.userEmail;
까리하다 주함... 감쟈해욤💭

2022-08-25 12:38 UTC, NaveOWO commented on src/components/JoinPage/EmailConfirm/index.tsx
> +  return (
이메일을 잘못 입력해서 전송이 안됐을 수도 있어서 다시 입력해야 한다고 생각했는데, 다시보니 너무 내맘대로 했네 ㅋㅋㅋㅋ
기획팀에 확인해보고 수정하겠슴미당! 지적 감사해용!

2022-08-25 12:39 UTC, joohaem commented on src/components/JoinPage/ErrorPopup/style.ts
> +    width: 100%;
코드 한 줄이긴 하지만, 속성을 부여하는 불필요한 프로세스가 진행될테니까요!

2022-08-25 12:39 UTC, NaveOWO commented on src/components/JoinPage/EmailConfirm/style.ts
> +    //프로토타입 없음
theme 에 프로토타입 만들라는 뜻이죠!? 채민이가 슬랙 답장을 아직 안줘서 기다리는 중이었슴딩 히히 추가할께요!

2022-08-25 12:39 UTC, NaveOWO commented on src/components/JoinPage/ EmailAuthentication/style.ts
> +    width: 1.7rme;
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ레전드 사랑해💙

2022-08-25 12:43 UTC, joohaem commented on src/components/JoinPage/ErrorPopup/index.tsx
> +  const { isPopupOpen, setIsPopupOpen } = props;
저도 29기 때 주입적으로 배웠던 내용이긴 하지만 추측하기로는,

함수를 감사서 내려주는 경우에는 그 함수만을 추적하여 state 가 변경되는 곳을 확인할 수 있지만,

state가 정말 core한 내용이라면, setState 를 내려주어 어디서든 변경할 수 있게끔 하는 것은 위험성이 높고,
어떠한 동작을 하는 것을 명시한 함수가 아닌 state를 바꾸는 setState를 사용하는 것이 의미적으로도 유지보수에 불리하다

이정도로 이해를 했어요! 느낌이 좀 와닿나요??!

2022-08-25 12:53 UTC, joohaem commented on src/Router.tsx
> +        <Route path={routePaths.EmailConfirm} element={PublicRoute({ Component: <EmailConfirmPage /> })} />
아하!!!
 
1. join 페이지에 authentication, confirm 을 컴포넌트만 바꾸도록 처리하는 건 어떤가요??!
2. join 페이지만 Route로 사용하고 그 내에 authentication, confirm, ... 를 sub routing 한다
이런 방법은 어떨까 해요!

그 이유는
이메일 인증, 확인, 정보 입력, 확인 창이 각각의 url 을 갖게 될텐데,
다른 페이지들의 url 계층과는 달리 회원가입만 여러 개의 url 을 사용하는 것이 통일성을 해친다는 생각에서 비롯되었어요!

어떻게 생각하시나요??👀👀

2022-08-25 12:57 UTC, joohaem commented on src/components/JoinPage/ EmailAuthentication/index.tsx
> +      });
저도 확신이 없이 코멘트 했던거라,,.^~
navigate state 로 url 를 건너뛰며 넘겨주는 것이 props 보다 불안정하다라는 킹리적 노갓심이 있었나봐요,!
단순 string 하나의 객체라면 문제가 없을 것 같습니다!!!
혼란을 드려 제송,,,

2022-08-25 19:07 UTC, NaveOWO commented on src/components/JoinPage/ErrorPopup/index.tsx
> +  const { isPopupOpen, setIsPopupOpen } = props;
완.전.요.
함수만 추적할 수 있다는것도 필요성 완전공감임미다🌟
주입완료 설명 고마워요!!🔥

2022-08-25 19:15 UTC, NaveOWO commented on src/components/JoinPage/ EmailAuthentication/index.tsx
> +    const email: string | null = emailInput.current && emailInput.current.value;
갑자기 궁금해졌는데, `null 타입을 옵셔널로 정의하는 이유는 무엇인가요?`질문의 이유가 궁금해요!
email에 null값이 오면 안된다고 생각해서인지, 아니면 null값이 올리가 없다고 생각해서인지 아니면 다른이유인지 아니면 그냥인지!

2022-08-25 20:10 UTC, NaveOWO commented on src/Router.tsx
> +        <Route path={routePaths.EmailConfirm} element={PublicRoute({ Component: <EmailConfirmPage /> })} />
저도 고민을 많이 했었는데..!! 
`다른 페이지들의 url 계층과는 달리 회원가입만 여러 개의 url 을 사용하는 것이 통일성을 해친다`--> 완전 동의해요!

모든 뷰를 페이지로 만들었던 이유는,

사용자 경험을 고려했을 때, `이메일인증` -> `아이디/비번설정` -> `프로필설정` -> `약관동의` 순으로 회원가입을 하다가 전 단계로 돌아가고싶을 때, (만약 컴포넌트를 바꾸는 구조로 구현되어있다면) `Header의 뒤로가기`를 클릭하면서 동적으로 컴포넌트를 바꿔주는 것일 텐데!
  1. `Header의 뒤로가기를 클릭하면서 동적으로 컴포넌트를 바꿔주는 것일 텐데!` --> 이게 되나1? 
  2. 된다고 해도, `Header의 뒤로가기` 와 `브라우저 자체의 뒤로가기` 를 클릭했을 때의 이동하는 페이지가 다를텐데 편리한 UX가 아니지 않을까? 라고 생각했기 때문이에요!

제가 알고있는게 틀렸다면 짚어주세요!🥺
그리구 다음 뷰가 급하기 때문에 오빠가 말한대로 컴포넌트 바꾸는 형식으로 바꿔볼께욧!!!

2022-08-26 04:45 UTC, joohaem commented on src/components/JoinPage/ EmailAuthentication/index.tsx
> +    const email: string | null = emailInput.current && emailInput.current.value;
👀반영 제안👀

오호! 당시에 null 값을 포함한 변수 선언이 조금 어색했어요!
그래서 아래와 같은 코드를 생각하고 물어봤던 것이었습니다!

```suggestion
    if (!emailInput.current) return;
    
    const email: string =  emailInput.current.value;
```

이렇게 하면 email 이 null 임을 계속 확인할 필요 없으니까요!

2022-08-26 04:47 UTC, joohaem commented on src/Router.tsx
> +        <Route path={routePaths.EmailConfirm} element={PublicRoute({ Component: <EmailConfirmPage /> })} />
브라우저의 뒤로 가기 동작을 고려하셨다니!!! 멋져요👍👍 고려하지 못했네요

그렇다면 더더욱 **sub routing** 이 좋다고 생각합니다 !
라우팅 위계의 통일성 + 뒤로 가기 동작 구현 둘 다 잡을 수 있으니까요 !

이는 수정하기 어렵지 않으니 하던 방식대로 진행해주셔도 좋을 것 같아요!!!

2022-08-30 05:09 UTC, joohaem reviewed
적극적인 리뷰 반영 감사합니다🙏🙏

#### ⁉ 질문사항
이후에 회원가입을 마지막 POST 시키는 통신에,
이메일, 세부 정보 등등의 정보를 모두 포함시킨 body가 필요할텐데
이메일 정보를 계속해서 navigate state로 보내주실 계획이신지 궁금합니다!!

2022-08-30 05:09 UTC, joohaem commented on src/style/theme.ts
> +  caption05: FONT({ weight: 700, size: 1.2, lineHeight: 140, letterSpacing: 4 }),
오마이갓 이런 프로토타입이 추가되었나요 ?????

🚨 디자인팀에게 형식에 맞춰서 프로토타입 이름 다시 지어달라고 요청해주실 수 있으실까요??

2022-08-30 05:09 UTC, joohaem commented on src/components/JoinPage/ EmailAuthentication/index.tsx
> +    }
```suggestion
    if (emailInput.current && emailInput.current.value) {
      setEmailText(emailInput.current?.value);
      setIsEmailInValid(false);
    } else {
      setIsEmailInValid(true);
    }
```

2022-08-30 05:09 UTC, joohaem commented on src/components/JoinPage/ EmailAuthentication/index.tsx
> +    }
에러를 풀어주는 로직도 필요할 것 같네요!

2022-08-30 05:09 UTC, joohaem commented on src/components/JoinPage/ EmailAuthentication/index.tsx
> +    }
근데 Invalid 아니구 왜 InValid 인가요??!😂😂

2022-09-01 07:23 UTC, merged