Feat/#145 join agree
TeamPiickle/client pull request #148
Opened 2022-08-23 08:40 UTC by NYeonK

- [ ] 브랜치명, 브랜치 알맞게 설정
- [ ] Reviewer, Assignees, Label, Milestone, Issue(PR 작성 후에) 붙이기
- [ ] PR이 승인된 경우 해당 브랜치는 삭제하기

## 📌 내용

- 회원가입 약관동의 페이지 구현 + 대략 24시간,,?,,근데 미완,,,
- 지원서 먼저 써야할 것 같아서 pr 날립니다!
- 완성 덜 된 부분 : 전체 동의 선택/해제, 체크누르면, 글씨색 변경, active아닐 때 회원가입 버튼 안눌리게 하기

<br />

## 📌 내가 알게 된 부분

- 너무 많아서 다 되면 정리할게욤!

<br />

## 📌 질문할 부분 

- 전체 동의 선택/해제하는 거 로직 어떻게 짜면 좋을까요?? 이것저것 시도해봤는데, 으렵네요😂😂
전체 선택이 되고 난 후에 아무 버튼을 누르면 전체 동의가 해제되어야 하는데 이게 일단 안되더라구요!

<br />

## 📸 스크린샷

<img src="https://user-images.githubusercontent.com/71490862/186111913-f2e31775-22c3-4ee8-8f20-ba608b54781f.gif" width=60% />

2022-08-25 05:55 UTC, joohaem requested changes
끈기 있게 작업하는 모습 대단합니다....👍👍👍😂🔥
멋지고 든든하고 고마워요!!!!!

아래 코멘트들 달았으니 모두 받아들이지는 말고,
같이 공부하고 이야기 나눠봤으면 합니다!

화이팅이에요⚡⚜

---
저라면 아래와 같이 구현할 것 같습니다!

```javascript
  const [isPicked, setIsPicked] = useState({
    first: false,
    second: false,
    third: false,
  });
```
state 하나만 선언한 후에,

각각의 svg 파일을 first, second, third 값으로 변경하여 렌더링합니다
ex) jsx 내에서 `isPicked.first ? <IcFullCheckBox /> : <IcEmptyCheckBox />`

전체 선택 해제는
`first && second && third ? <IcFullCheckBox /> : <IcEmptyCheckBox />` 로 렌더링하고,
onClicked 핸들링은 
```javascript
// first && second && third 이라면 아래 객체를 setIsPicked
{
    first: false,
    second: false,
    third: false,
  }

// 아니라면 아래 객체를 setIsPicked
{
    first: true,
    second: true,
    third: true,
  }
```
로 할 것 같습니다

2022-08-25 05:55 UTC, joohaem commented on src/Router.tsx
> +        <Route path={routePaths.Join} element={PublicRoute({ Component: <JoinPage /> })} />
🚨반영 필요🚨

Join 페이지 형식 맞춰서 만들어 논 거 완전 감동이야!!!!! 👍👍 (지영이랑 코드가 겹칠 것 같기도 하고?)

하나 추가하자면, 회원가입은 로그인을 했을 시에 접근하지 못하도록 하는 페이지라서,
아래와 같이 restirced 인자를 추가로 넘겨줘야 접근을 제한할 수있도록 해놨어 !!
{PublicRoute({ Component: <JoinPage /> })} --> {PublicRoute({ Component: <LoginPage />, restricted: true })}

2022-08-25 05:55 UTC, joohaem commented on src/Router.tsx
> +        <Route path={routePaths.Join} element={PublicRoute({ Component: <JoinPage /> })} />
👀반영 제안👀

더불어서 지영이랑 얘기해서 이것도 논의해봐!

회원가입이라는 공통의 테마임에도 join, agree, certification 이런 식으로 라우팅이 나뉘어져 있는데
이를 sub routing 으로 묶어봄이 어떨까??
예를 들어 join/agree, join/certification 이런 식으로 !!

2022-08-25 05:55 UTC, joohaem commented on src/components/JoinPage/JoinAgree/index.tsx
> +  const [allPicked, setAllPicked] = useState(false);
🚨반영 필요🚨

굳이 state를 따로 만들지 않아도, `first && second && third` 표현의 변수를 선언해서 처리할 수 있지 않을까?

state를 분리하면 할 수록 렌더링의 경우의 수가 늘어난다는 걸 생각해봤을 떄!

2022-08-25 05:55 UTC, joohaem commented on src/components/JoinPage/JoinAgree/index.tsx
> +  ]);
🚨반영 필요🚨

state로 선언한 이유가 있을까요?
계속해서 렌더링 될 필요 없는 선언인 듯 보입니다! 컴포넌트 밖으로 빼주세요

2022-08-25 05:55 UTC, joohaem commented on src/components/JoinPage/JoinAgree/index.tsx
> +  ]);
🚨반영 필요🚨

lists 로는 어떤 리스트인지 명확하지 않아보입니다
좀 더 서술하는 변수명으로 선언해주세요!!

2022-08-25 05:55 UTC, joohaem commented on src/style/theme.ts
> +  h1: FONT({ weight: 600, size: 2.6, lineHeight: 140, letterSpacing: 4 }),
또 바꼈나요 이거??😂😂😂😂

2022-08-25 05:55 UTC, joohaem commented on src/components/JoinPage/JoinAgree/style.ts
> +    width: 100%;
🚨반영 필요🚨

`width: 100%` 는 기본값으로, 불필요한 css 속성인 듯 합니다

2022-08-25 05:55 UTC, joohaem commented on src/components/JoinPage/JoinAgree/index.tsx
> +  const [allPicked, setAllPicked] = useState(false);
오호 number 로 바꿨구나!

2022-08-25 05:55 UTC, joohaem commented on src/components/JoinPage/JoinAgree/style.ts
> +  JoinButton: styled.button`
변수명 구욷👍👍👍

2022-08-25 05:55 UTC, joohaem commented on src/components/JoinPage/JoinAgree/index.tsx
> +      <St.JoinButton onClick={() => (location.href = "")}>회원가입 완료하기</St.JoinButton>
`Link` 혹은 `useNavigate` 를 이용해주세요
window 객체의 location 을 통한 링크 이동은 리액트에서 잘 사용하지 않습니다

2022-08-25 05:55 UTC, joohaem commented on src/components/JoinPage/JoinAgree/index.tsx
> +  }
👀반영 제안👀

```suggestion
  const alertClassName = openAlert === false ? "login-alert" : "login-alert-view";
```

이렇게 선언하면 되지 않을까 합니다!

2022-08-25 05:55 UTC, joohaem commented on src/components/JoinPage/JoinAgree/style.ts
> +    }
🚨반영 필요🚨

styled-components 내에서 불필요한 클래스 사용을 지양해주세요

SC의 props 로 `isalert` 를 받아 사용함이 어떨까 합니다!!

2022-08-30 04:58 UTC, joohaem requested changes
끈기있게 해주시는 모습 넘나 대단하십니다👍👍👍👍

2022-08-30 04:58 UTC, joohaem commented on src/components/JoinPage/JoinAgree/index.tsx
> +  }, [isPicked, isPickedItems]);
state 값 변경은 setState 를 통해 이루어져야 정상적인 리렌더링이 동작합니다!

2022-08-30 04:58 UTC, joohaem commented on src/components/JoinPage/JoinAgree/index.tsx
> +      <St.ModalContainer className={alertClassName}>이용약관에 동의해주세요</St.ModalContainer>
동적 스타일링은 클래스 네임이 아니라, styled-components 의 props 방법을 이용해서 진행하는 게 통일성 있어 보입니다!! 
통일성이 없는 코드로 구현되게 되면 이후의 유지보수가 불편해지는는 문제가 있을 수 있어요

2022-08-30 04:58 UTC, joohaem commented on src/components/JoinPage/JoinAgree/index.tsx
> +  }, [isPickedItems, openAlert]);
무엇을 의미하는 코드인지 설명 한 번만 부탁드려도 될까요???😂😂

2022-08-30 04:58 UTC, joohaem commented on src/components/JoinPage/JoinAgree/index.tsx
>    const [isPickedItems, setIsPickedItems] = useState([
제 생각에는 ... 불필요한 state 가 계속 생긴다고 생각 들어요
state 가 많아질 수록, 리렌더링을 위해 우리가 관리해야 하는 변수들이 많아진다는 의미인데,
이를 통합할 수 있는지 생각을 해봐야 할 것 같습니다

![image](https://user-images.githubusercontent.com/47105088/187352132-d108a4c6-6125-44de-93d7-9be491d346a9.png)

위는 제가 처음에 달았던 코멘트인데 같은 맥락으로 현재 코드의 우려되는 부분들을 얘기해볼게요!

1. `isPicked` 라는 state 가 불필요해 보입니다
  map을 이용한 `agreeList` 의 이벤트가 발생한 index 값으로 충분히 몇 번째 인덱스인지 유추가 가능할 것 같아요
  그럼에도 state 를 추가할 경우에는, isPicked 를 조작하고, 그에 따른 items 를 조작하고, ... 하면서 휴먼 에러가 발생할 가능성이 커진다고 생각합니다
2. `isAllPicked` 라는 state 가 불필요해 보입니다
  "items 의 state가 모두 true이냐" 정도로 판별이 가능할 것 같습니다
  1번과 같은 이유입니다
3. `openAlert` 변수명을 boolean 에 맞게 `isOpenAlert` 정도로 변경하심이 어떨까 합니다

2022-08-30 05:48 UTC, NYeonK commented on src/components/JoinPage/JoinAgree/index.tsx
> +  }, [isPicked, isPickedItems]);
아항!! 고치겠습니다~!~!!!

2022-08-30 05:50 UTC, NYeonK commented on src/components/JoinPage/JoinAgree/index.tsx
> +      <St.ModalContainer className={alertClassName}>이용약관에 동의해주세요</St.ModalContainer>
넵! 저번 코드리뷰 때도 달아주셔서 어떻게 하는지 공부하거 있어욤><

2022-08-30 05:52 UTC, NYeonK commented on src/components/JoinPage/JoinAgree/index.tsx
> +  }, [isPickedItems, openAlert]);
필수 약관들에 동의를 하지 않으면, 동의하라는 메세지를 띄워 놓는 코드입니다~!~!!
근데 지울 것 같아요!! 기획에서 메세지 언제 띄우는지 오늘 다시 알려준다고 했습니당 :D

2022-08-30 05:59 UTC, NYeonK commented on src/components/JoinPage/JoinAgree/index.tsx
>    const [isPickedItems, setIsPickedItems] = useState([
1번의 `isPicked`는 useEffect에서 index를 어떻게 가져와야 할지 몰라서 만들었습니다!! 제가 선택한 체크박스의 인덱스를 useEffect에는 어떻게 가져올 수 있을까요?!!
코드리뷰를 보고, `currentList[1].state && currentList[2].state && currentList[3].state && currentList[4].state` 이런 식으로 했는데 작동이 잘 안돼서 `isAllPicked`를 만들게 되었습니당ㅠㅠ
3번 반영하겠습니다아 감사합니다!!!!

2022-08-30 10:57 UTC, NaveOWO reviewed
고나리연 너무 수고햇다🥺 진짜 어려웠겟당!!!! 그래도 피알 올린거 너무 멋쪙!!!!!!🔥🔥
코드 보면서 많이 배워가욤ㅇㅅㅇ
그리구 수정사항 다 반영하구 마지막 피알 올리면 말해조!! 페이지구조랑 route 써놓은것들 먼저 맞춰서 conflict 줄이게..ㅋㅋㅋㅋㅋㅋ
므찌다!!!!!!!!!!!!!!!!!!

2022-08-30 10:57 UTC, NaveOWO commented on src/@components/JoinPage/JoinAgree/index.tsx
> +        isPickedItems[4].state = true;
이렇게 컴포넌트 순서대로 같은 값으로 변경할 때, for문 사용하지 않고 각각 변경해준 이유가 있을까욤!? 
(약관이 추가 될 가능성은 없지만!) 확장성을 고려했을 때, 일일히 바꿔주는 건 비효율적이라고생각해서!!🙈

2022-08-30 10:57 UTC, NaveOWO commented on src/@components/JoinPage/JoinAgree/index.tsx
> +    return A === B ? setAllIsPicked(true) : setAllIsPicked(false);
변수명을 A, B 로 설정한 이유가 궁금해요!

2022-08-30 10:57 UTC, NaveOWO commented on src/style/theme.ts
> +  h1: FONT({ weight: 600, size: 2.6, lineHeight: 140, letterSpacing: 4 }),
매의눈이네 바뀐거 어케알앗오👍👍

2022-08-30 23:57 UTC, NYeonK commented on src/@components/JoinPage/JoinAgree/index.tsx
> +    return A === B ? setAllIsPicked(true) : setAllIsPicked(false);
변경하겠습니다ㅎㅎㅎㅎㅎㅎ🧡

2022-08-30 23:59 UTC, NYeonK commented on src/@components/JoinPage/JoinAgree/index.tsx
> +        isPickedItems[4].state = true;
기능 만들기에 급급해서 for문 생각을 못했네요!! 반영하겠습니다!!! 감사합니당!!!

2022-08-31 06:15 UTC, joohaem commented on src/@components/JoinPage/JoinAgree/index.tsx
> +        }
state 를 직접 수정하는 이유는 뭘까요 ,,? setState 를 이용하지 않는 이유가 있을까요?

2022-08-31 06:15 UTC, joohaem commented on src/@components/JoinPage/JoinAgree/index.tsx
> +  }, [isPickedItems, openAlert, isAllPicked]);
변수명은 카멜케이스로, 소문자로 시작하는 것이 저희 컨벤션으로 알고 있습니다!

2022-08-31 14:43 UTC, NYeonK commented on src/@components/JoinPage/JoinAgree/index.tsx
> +  }, [isPickedItems, openAlert, isAllPicked]);
옷 호딱 고치겠습니다..!!!!!!!😅😅

2022-08-31 14:43 UTC, NYeonK commented on src/@components/JoinPage/JoinAgree/index.tsx
> +        }
아직 변경을 안한 거였어소, 반영했습니다!!!😋😆

2022-09-01 06:12 UTC, joohaem commented
LGTM👍👍👍👍아따 잘한다!!

2022-09-01 15:24 UTC, joohaem approved these changes
⁉ Question 
언제쯤에 수정이 완료되고 머지가 될 예정이실까요???

2022-09-01 18:22 UTC, merged