Feat/#152 user info
TeamPiickle/client pull request #156
Opened 2022-09-05 16:17 UTC by NaveOWO

- [ ] 브랜치명, 브랜치 알맞게 설정
- [ ] Reviewer, Assignees, Label, Milestone, Issue(PR 작성 후에) 붙이기
- [ ] PR이 승인된 경우 해당 브랜치는 삭제하기

## 📌 내용

- 

<br />

## 📌 내가 알게 된 부분

- 

<br />

## 📌 질문할 부분 

- 

<br />

## 📸 스크린샷

<img src="" width=80% />

2022-09-07 17:02 UTC, joohaem requested changes
리뷰를 원하지 않는 PR 에 대해서는, Draft PR 로 요청해주시길 바랍니다!

2022-09-07 17:02 UTC, joohaem commented on src/@components/JoinPage/common/SuccessBtn/index.tsx
> +}
✔ props 컨벤션 지켜주세요!
아래 suggestion 그대로 올리셔도 좋을 것 같습니다

```suggestion
export default function SuccessBtn(props: ButtonContentsProps) {
  const { name } = props;
  
  return <St.SuccessButton>{name}</St.SuccessButton>;
}
```

2022-09-10 02:13 UTC, joohaem reviewed
LGTM !! 멋져요 🗼

2022-09-10 02:13 UTC, joohaem commented on src/@components/JoinPage/UserInfoPage/UserPassword/index.tsx
> +  }, [debouncedQuery]);
LGTM 👍👍👍 깔끔ㅎ한데요!!!?

2022-09-10 02:13 UTC, joohaem commented on src/@components/JoinPage/UserInfoPage/UserPassword/index.tsx
> +  const [currentStep, setCurrentStep] = useState("input");
✨ 반영 제안 ✨

해당 state의 타입이 string으로 정의되어 있기 때문에, input/confirm 이외에도 다른 값이 들어갈 수 있어요

이를 막기 위해 <"input" | "confirm"> 이런 식으로 타입 지정을 하면 좋을 것 같습니다!
또, 이런 타입 지정을 관리하기 위해 enum, const enum 개념도 있으니 알아보면 좋을 것 같아요!
[🔗 enum](https://snupi.tistory.com/202)

2022-09-10 16:25 UTC, NaveOWO commented on src/@components/JoinPage/common/SuccessBtn/index.tsx
> +}
에구궁.. 컨벤션이었구나 제송함미다...ㅇㅅㅇ

2022-09-10 16:28 UTC, joohaem requested changes
🗼 가파르게 성장하는 게 보이네요 ! 🗼

2022-09-10 16:28 UTC, joohaem commented on src/@components/JoinPage/UserInfoPage/UserPassword/index.tsx
> +      setIsPasswordInvalid((prev) => [true, prev[1]]);
`prev[1]` 보다 스프레드 연산자를 활용하심은 어떨까요?

2022-09-10 16:28 UTC, joohaem commented on src/core/api/join.ts
> +};
뀼! 통일성 좋아요!!!

2022-09-10 16:28 UTC, joohaem commented on src/@components/JoinPage/UserInfoPage/index.tsx
> +          />
오우 ... 비대한 props 로 보아
컴포넌트 로직이 과하게 뭉쳐있다고 생각듭니다

기능별로 더 분리하심이 어떨까요?

2022-09-10 17:00 UTC, NaveOWO commented on src/@components/JoinPage/UserInfoPage/UserPassword/index.tsx
> +  const [currentStep, setCurrentStep] = useState("input");
넴넴!! 요거 너무 궁금했어요!! 감사해욤👍

2022-09-10 17:09 UTC, NaveOWO commented on src/@components/JoinPage/UserInfoPage/index.tsx
> +          />
이게..!! setState를 프롭스로 안넘기고 setState를 이용하는 함수들을 모두 props로 넘기려다보니깐 모든 프롭스들이 한곳에 뭉쳐져버렸는데... 함수 자체를 더 분리하는게 좋을 것 같다는 뜻일까요1?

2022-09-10 17:20 UTC, NaveOWO commented on src/@components/JoinPage/UserInfoPage/UserPassword/index.tsx
> +      setIsPasswordInvalid((prev) => [true, prev[1]]);
으악? 스프레드 연산자 사용하고싶었는데 저부분에는 전 배열에서의 부분만 들어가는거라서 어떻게 하는지 몰랐어요... 스프레드 연산잔데 부분만 사용할 수 있나요..!?

2022-09-12 01:44 UTC, joohaem reviewed
🔥🔥🔥🔥

2022-09-12 01:44 UTC, joohaem commented on src/types/users.ts
> +}
`null` 인 경우가 있을까요 ??!
빈 문자열일 경우에 에러메시지로 처리되지 않는 건가요!

2022-09-12 01:44 UTC, joohaem commented on src/@components/JoinPage/UserInfoPage/index.tsx
> +      email: localStorage.getItem("user-email"),
localStorage 로 하는 부분들에 대해서 주석 하나씩만 달아주세요 !!
이후에 확인하기 쉽도록 !

ex)
// TODO :: outlet context 로 치환

2022-09-12 01:48 UTC, joohaem commented on src/@components/JoinPage/UserInfoPage/index.tsx
> +          />
`input` 과 `confirm` 이 같은 로직으로 부분부분 변경만 되는 것 같아요
이를 한 컴포넌트를 재사용함으로써 중복을 제거할 수 있지 않을까 합니다!

2022-09-12 01:54 UTC, joohaem commented on src/@components/JoinPage/UserInfoPage/UserPassword/index.tsx
> +      setIsPasswordInvalid((prev) => [true, prev[1]]);
@NaveOWO 
다시 확인해봤는데, 데이터의 무결성 측면에서 배열보다 객체형태로 가심이 좋을 것 같아요!
배열의 길이도 변할 수 있고, 각 위치의 접근도 어려울 수 있기 때문에

```javascript
{
  input: false,
  confirm: false
}
```

처럼 해두면,
활용할 때에도

```javascript
{
  ...prev,
  input: true
}
```

식으로 스프레드 연산자를 활용하여 불변성 문제도 해결할 수 있을 것 같습니다!

2022-09-12 02:03 UTC, joohaem commented
> 다음으로버튼 이나 비밀번호 입력칸 같이 여러 컴포넌트에서 공통적으로 쓰이는 요소들은 common으로 빼서 재사용을 하고싶었는데, 스타일링만 같고, 요소에 해당하는 함수&로직들이 다 달라서 공통으로 쓰는걸 실패했는데요.. 이런 경우에도 common으로 빼는게 맞았나요?

옹 맞아요!!!! `join` 폴더 안에 `@common` 에 빼주면 좋을 것 같습니다!!! 
(지금 common 폴더가 있네요! 이거 @common 으로 폴더명 수정하는 게 맨 위로 올라와서 더 보기 좋더라구요옷)

---

> constants.ts 파일에 앞에 /users/가 겹칠 때 일일히 써주지 않는 방법이 있는 것 같은데 모르겠어요..!

미친!!!!!!! 멋져요⚡ 이런 생각을 하시다니!
저도 지금 제대로 살펴봤는데,
지금 /users 인 게 있으니까 
`USERS` -> `USERS_`
`EMAIL` -> `USERS_EMAIL` :: `/users/email-verification` -> `/email-verification`

로 수정하고,
`${PATH.USERS_}${PATH.USERS_EMAIL}`
이렇게 사용하심이 어떨까 합니다!

join 을 sub routing 하면서
route/path 에서도 이렇게 사용했던 것 같아요!

2022-09-12 16:20 UTC, NaveOWO commented on src/@components/JoinPage/UserInfoPage/index.tsx
> +          />
오호 그렇군요!! 수정 해볼께요!!

2022-09-12 16:40 UTC, NaveOWO commented on src/types/users.ts
> +}
email에 query를 할당한느데, query가 null 이랑 string 둘다 가질 수 있어서 타입을 저렇게 지정했어요! 근데 null에 이메일 전송하는건 말이 안되네욤.. 수정해보겠슴미다🌟

2022-09-16 02:24 UTC, joohaem approved these changes
LGTM👍👍
아래 PR 에서 통합 작업하였으니, 해당 PR은 Close 하겠습니다!

https://github.com/TeamPiickle/client/pull/159

2022-09-16 02:25 UTC, closed without merging