Feat/#154 user profile
TeamPiickle/client pull request #157
Opened 2022-09-09 19:53 UTC by NYeonK

- [ ] 브랜치명, 브랜치 알맞게 설정
- [ ] Reviewer, Assignees, Label, Milestone, Issue(PR 작성 후에) 붙이기
- [ ] PR이 승인된 경우 해당 브랜치는 삭제하기

## 📌 내용

- 프로필 설정 뷰 구현

<br />

## 📌 내가 알게 된 부분

- 

<br />

## 📌 질문할 부분 

- 

<br />

## 📸 스크린샷

<img src="" width=80% />

2022-09-12 16:13 UTC, joohaem requested changes
🗼 고나연이 최고다 🗼👍👍👍👍

중간 리뷰 남겨놨어요!

수정하던 부분들 수정하고, 필요한 부분 제가 마무리 작업하도록 할테니
부담 없이 진행해줘요 !!!!@~

2022-09-12 16:13 UTC, joohaem commented on src/@components/JoinPage/UserProfilePage/ProfileBirth/index.tsx
> +export default function ProfileBirth(props: birthTypes) {
⚡반영 필요⚡--> `commit suggestion`

props 타입 컨벤션 지켜주세요!

```suggestion
interface ProfileBirthProps {
  isbirth: string;
  setIsbirth: (birthDay: string) => void;
}

export default function ProfileBirth(props: ProfileBirthProps) {
```

2022-09-12 16:13 UTC, joohaem commented on src/@components/JoinPage/UserProfilePage/ProfileJender/index.tsx
> +export default function ProfileJender(props: jenderTypes) {
⚡반영 필요⚡--> `commit suggestion`

```suggestion
interface ProfileJenderProps {
  isSelected: string;
  setIsSelected: (jender: string) => void;
}

export default function ProfileJender(props: ProfileJenderProps) {
```

2022-09-12 16:13 UTC, joohaem commented on src/@components/JoinPage/UserProfilePage/ProfileNickname/index.tsx
> +export default function ProfileNickname(props: nickNameTypes) {
```suggestion
interface ProfileNickname {
  nickName: string;
  setNickName: (nickName: string) => void;
  isChecked: boolean;
  setIsChecked: (button: boolean) => void;
}

export default function ProfileNickname(props: ProfileNickname) {
```

2022-09-12 16:13 UTC, joohaem commented on src/@components/JoinPage/UserProfilePage/ProfileNickname/style.ts
> +  NickNameInputForm: styled.input<{ nickName: string; isChecked: boolean; isInComplete: boolean; isError: string }>`
⚡반영 필요⚡

css 가 해당 조건들을 알 필요 없이, isIncompleteState 인지, isErrorState 인지만 알 면 기능 분리가 잘 될 것 같아요!
이를 넘겨줄 때 `isincompletestate={nickName === "" && isIncomplete} iserrorstate={isChecked && isError}` 로 넘겨주면 될 것 같습니다

2022-09-12 16:13 UTC, joohaem commented on src/@components/JoinPage/UserProfilePage/ProfileBirth/index.tsx
> +  setIsbirth: (birthDay: string) => void;
setState 가 이 타입으로 되나요,,?!

2022-09-12 19:48 UTC, NYeonK commented on src/@components/JoinPage/UserProfilePage/style.ts
> +  Title: styled.strong``,
오엥?!?!? 확인해보겠습니다😋😋

2022-09-12 19:51 UTC, NYeonK commented on src/@components/JoinPage/UserProfilePage/index.tsx
> +  const [isbirth, setIsbirth] = useState<string>("");
우왓 그런 걸 생각해본 적은 없는데, 그렇네여????!!
바아아아로 반영하겠습니다!! (≧∀≦)ゞ

2022-09-12 19:53 UTC, NYeonK commented on src/@components/JoinPage/UserProfilePage/ProfileBirth/index.tsx
> +export default function ProfileBirth(props: birthTypes) {
넵!!!!!😎😎😎

2022-09-12 19:55 UTC, NYeonK commented on src/@components/JoinPage/UserProfilePage/ProfileBirth/index.tsx
> +  setIsbirth: (birthDay: string) => void;
아주 잘...되던데.... 보통 어케 쓰나여??! 👀👀

2022-09-12 19:59 UTC, NYeonK commented on src/@components/JoinPage/UserProfilePage/ProfileNickname/style.ts
> +  NickNameInputForm: styled.input<{ nickName: string; isChecked: boolean; isInComplete: boolean; isError: string }>`
얼....오빠는 혹시 천재인가......? (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧

2022-09-12 20:03 UTC, NYeonK commented on src/@components/JoinPage/UserProfilePage/ProfileNickname/style.ts
> +    width: calc(94% - 29.9rem);
제 감으로 넣었습..니다....ㅎㅎ
input이랑 button 태그를 나란히 놓아야 하는데, 100%으로 하니까 잘 안돼서 수정해봤.....><

2022-09-13 03:08 UTC, joohaem commented on src/@components/JoinPage/UserProfilePage/ProfileNickname/style.ts
> +    width: calc(94% - 29.9rem);
@NYeonK 
><.....>~^^

2022-09-13 03:10 UTC, joohaem commented on src/@components/JoinPage/UserProfilePage/ProfileBirth/index.tsx
> +  setIsbirth: (birthDay: string) => void;
setState 를 props 로 계속 내려주게 되면, state 가 어디서 변경되는지 추적하기 힘들어져서 유지보수가 어려워져요!
이를 방지하기 위해 setState를 직접 내려주지 않고, 
`handleBirthData` 와 같은 함수를 선언하고
그 안에서 setState 로 state 를 변경하는 로직을 작성하고
선언한 함수를 내려주는 게 좋아보여요!

2022-09-16 02:25 UTC, joohaem approved these changes
LGTM👍👍
아래 PR 에서 통합 작업하였으니, 해당 PR은 Close 하겠습니다! 고생했ㅆ어요ㅠㅠㅜ고마오

https://github.com/TeamPiickle/client/pull/159

2022-09-16 02:25 UTC, closed without merging