Feat/#185 moodpiickle design
TeamPiickle/client pull request #186
Opened 2023-01-21 20:10 UTC by NYeonK

- [x] 브랜치명, 브랜치 알맞게 설정
- [x] Reviewer, Assignees, Label, Milestone, Issue(PR 작성 후에) 붙이기
- [ ] PR이 승인된 경우 해당 브랜치는 삭제하기

## 📌 내용

- MoodPiickle 페이지의 배너 수정 및 이모지를 추가했습니다!
- 그라데이션 배경은 아직 반영 x

<br />

## 📌 내가 알게 된 부분

- 추가 예정

<br />

## 📸 스크린샷

<img src="https://user-images.githubusercontent.com/71490862/213885194-661f043a-8bcf-4ebb-94ff-7a201f4b4910.jpg" width=60% />

2023-01-22 11:33 UTC, joohaem approved these changes
고생해쒀요...!!!!! 
나중에 리뷰 남긴 거랑 그라데이션만 추가해서 머지합시다!

2023-01-22 11:33 UTC, joohaem commented on src/style/theme.ts
> +  body3: FONT({ weight: 500, size: 1.8, lineHeight: 140, letterSpacing: 3.5 }),
🚨
이거 3.5 아니라 35로 넣어줘야 해요!

2023-01-22 11:33 UTC, joohaem commented on src/style/theme.ts
> +  body3: FONT({ weight: 500, size: 1.8, lineHeight: 140, letterSpacing: 3.5 }),
letter-spacing: -0.0${letterSpacing}rem;

이렇게 되어있어서 -0.03.5rem 이 되어버립니다

2023-01-22 11:35 UTC, joohaem commented
더불어서, 배너 이미지가 width 720px 인데,
우리 서비스가 PC에서도 360px 을 안넘어서 이미지 작업 줄여달라고 제가 요청할게요!

유니코드랑 디자인/서버와 소통하면서 작업하시느라 고생 많으셨습니다😭😭😭

2023-01-22 11:36 UTC, joohaem requested changes
~더불어서, 배너 이미지가 width 720px 인데,
우리 서비스가 PC에서도 360px 을 안넘어서 이미지 줄여달라고 제가 요청할게요!~ => 보류

유니코드랑 디자인/서버와 소통하면서 작업하시느라 고생 많으셨습니다😭😭😭

2023-01-23 11:00 UTC, NYeonK commented on src/style/theme.ts
> +  body3: FONT({ weight: 500, size: 1.8, lineHeight: 140, letterSpacing: 3.5 }),
아 구렇구나,,! 잘못 표기된줄 알고 수정했오😅😅 바로 수정할게요오

2023-01-23 14:42 UTC, merged