Feat/#189 vote cta btn
TeamPiickle/client pull request #192
Opened 2023-02-01 19:57 UTC by NYeonK

- [x] 브랜치명, 브랜치 알맞게 설정
- [x] Reviewer, Assignees, Label, Milestone, Issue(PR 작성 후에) 붙이기
- [ ] PR이 승인된 경우 해당 브랜치는 삭제하기

## 📌 내용

- votePage의 CTA 버튼을 서비스 화면에 맞게 조절합니다.
- votePage CTA 버튼의 구분선이 스크롤링에 따라 움직이지 않도록 고정시킵니다.

<br />

## 📌 질문할 부분 

- 버튼이 `MoveBtn`으로 통일되어 있길래, props로 `beforeId={true/false}`로 구분지어서 스타일을 적용했습니당!
이전버튼과 다음버튼 두개의 태그로 나눠서 스타일링 하는 것보다 깔끔할 것 같아서 props를 썼는데 
어떠한 방식이 더 좋다~이런게 있을까요?-?

<br />

## 📸 스크린샷

<img src="https://user-images.githubusercontent.com/71490862/216148921-f8f65527-c67b-4cff-9843-8f8987c10947.png" width=40% />

2023-02-02 02:49 UTC, joohaem requested changes
리뷰로 남겼습니다 !!

2023-02-02 02:49 UTC, joohaem commented on src/@components/VotePage/VoteContent/style.ts
> +  width: 100%;
property 삭제해도 될 것 같아요 !

2023-02-02 02:49 UTC, joohaem commented on src/@components/VotePage/VoteContent/style.ts
> -  gap: 0.1rem;
gap을 더서 두 버튼 사이에 빈 공간 생기게 했던 건데, border로 작업한 이유가 있으실까요??!

2023-02-02 02:49 UTC, joohaem commented on src/@components/VotePage/VoteContent/index.tsx
> +          </St.MoveBtn>
(gap으로 작업하는 게 더 ㄷ깔끔할 것 같은데, 다른 이유가 있다면!!)

새 true, false로 고정된 props라면 줄 이유가 없다고 생각해요!

SC 객체를 두개로 분리함이 더 깔끔해보입니다
혹은, 중복되는 속성들을 한 SC로 분리하고
그 객체를 상속받아서 여러 객체로 사용하는 게 더 확장성 있는 코드가 될 것 같네요!

```typescript
const 부모객체 = styled.div`
  중복 프로퍼티...
`;

// export
const 자식객체1 = styled(부모객체)`
  추가 프로퍼티...
`;

// export
const 자식객체2 = styled(부모객체)`
  추가 프로퍼티...
`;
```

2023-02-03 01:24 UTC, NYeonK commented on src/@components/VotePage/VoteContent/style.ts
> +  width: 100%;
이 리뷰랑 밑에 `theme.media.desktop` 요 리뷰랑
둘이 동일한 QA 작업인ㄷ요!!

(기획 QA) 데스크탑으로 보면, 투표페이지 CTA 버튼이 모니터 넓이에 맞춰져 있다고 해서 
추가했습니다~

2023-02-03 01:32 UTC, NYeonK commented on src/@components/VotePage/VoteContent/style.ts
> -  gap: 0.1rem;
![image](https://user-images.githubusercontent.com/71490862/216489166-1d2102ad-c08c-4ccd-a05a-84b377e196bb.png)


gap 쓴거 똑똑하도라,,,
(디자인 QA) 사진처럼 스크롤 올리면 구분선이 위로 올라가버려서,  border로 작업했습니다~! 
gap이 더 깔끔하긴 해서, 좋은 방법이 있다면 추천부탁드림다 :D

2023-02-03 01:37 UTC, NYeonK commented on src/@components/VotePage/VoteContent/index.tsx
> +          </St.MoveBtn>
우왕 이렇게도 할 수 있는지 처음 알았네요!!! (이모티콘 쓰고 싶은데, 회사컴터는 `window+.`이 안먹네,,)

반영해서 다시 코드 작성해보겠습니다@!! 좋은 정보 감사합니다아><

2023-02-03 03:21 UTC, joohaem commented on src/@components/VotePage/VoteContent/index.tsx
> +          </St.MoveBtn>
@NYeonK 
주변에 있는 `NoLinkBtn` 같은 것들도 합쳐주세요 :)...

2023-02-03 03:22 UTC, joohaem commented on src/@components/VotePage/VoteContent/style.ts
> -  gap: 0.1rem;
왜 올라가버리는거지!!!!

2023-02-03 07:32 UTC, NYeonK commented on src/@components/VotePage/VoteContent/index.tsx
> +          </St.MoveBtn>
넴냐리~.~

2023-02-04 23:46 UTC, joohaem approved these changes
최고!!!!!!

2023-02-04 23:46 UTC, merged