Feat/#218 medley
TeamPiickle/client pull request #220
Opened 2023-03-08 17:33 UTC by NYeonK

- [x] 브랜치명, 브랜치 알맞게 설정
- [x] Reviewer, Assignees, Label, Milestone, Issue(PR 작성 후에) 붙이기
- [ ] PR이 승인된 경우 해당 브랜치는 삭제하기

## 📌 내용

- Medley 기능 구현

추가해야 하는 부분
- [ ] medley 그라데이션 따로 정리하기
- [ ] medley preview

<br />

## 📌 내가 알게 된 부분

- 

<br />

## 📌 질문할 부분 

- 

<br />

## 📸 스크린샷

<img src="https://user-images.githubusercontent.com/71490862/223786472-0cc6a239-ed02-4898-bd04-fd4d0d90f375.png" width=50% />

2023-03-09 01:27 UTC, joohaem requested changes
항상 예상을 뛰어넘는🔥 ........ 나연이의 실력🔥🔥🔥🔥 
최고다🦾🦾
앞으로 많이 부탁할게!!!!!!!!!!!!!!!!! 고생해쒀

1. `백그라운드 로직`
    이건 내가 생각 해봤는데, const 상수에 `Map` 객체를 사용해서
    key: 특정 메들리의 _id 값 / value: 백그라운드 칼라값
    으로 구성해서 이 객체를 불러다가 넣어주면 될 것 같아!!!!
    그러면 가영이가 원하는 디자인적인 요소의 분리도 이루어지고, 클라에서도 유연성 있게 설계가 될 것 같당

2. `로딩 로직`
    이건 내가 api들 다 swr로 치환하고, 로딩 로직들 Suspense로 치환하는 작업을 하려고 해!
    이번주 내로 해볼게 !!!

2023-03-09 01:27 UTC, joohaem commented on src/@components/MainPage/Medley/MedleyPreview/index.tsx
> +  };
이거를 useMedleyLists 훅 안에 넣어놔도 되겠다!
다른 것들도 다 그래야겠네 하하하~.~
1. string으로 직접 써주는 type 값을 const 상수로 빼내는 게 좋을 것 같다! 
2. setSliderIdx(0) 일 경우에, 안써도 되도록 하는 방안이 뭐가 있을까?
3. `moveMedley` -> `moveCardCollectionFromMedley` 같은 이름이 어떨지 ???

2023-03-09 01:27 UTC, joohaem commented on src/@components/MainPage/Medley/MedleyPreview/index.tsx
> +          })}
return 생략해도 될 것 같은데??!

```suggestion
          medleyLists.data.map((medleyLists) => 
            (
              <St.MedleyPreview key={medleyLists._id}>
                <St.Tag>{medleyLists.sticker}</St.Tag>
                <St.Title>{medleyLists.title}</St.Title>
                <St.Description>{medleyLists.description}</St.Description>
                <St.PreviewCards>
                  {medleyLists.previewCards.map((item: object, i: number) => 
                    (<St.CardWrapper key={i}>{medleyLists.previewCards[i].content}</St.CardWrapper>)
                  )}
                </St.PreviewCards>
                <St.MoveBtn onClick={() => moveMedley(medleyLists._id)}>카드 보기</St.MoveBtn>
              </St.MedleyPreview>
            )
          )}

```

2023-03-09 01:27 UTC, joohaem commented on src/@components/MainPage/Medley/index.tsx
> +
삭제 !

2023-03-09 01:27 UTC, joohaem commented on src/@components/MainPage/Medley/MedleyPreview/index.tsx
> +import React from "react";
삭제!

2023-03-09 01:27 UTC, joohaem commented on src/@components/MainPage/Medley/index.tsx
> +          <St.MedleyContainer isClicked={isModalOpen}>
`isClicked`는 없어도 될 것 같다? 그치??

2023-03-09 01:27 UTC, joohaem commented on src/@components/MainPage/Medley/index.tsx
> +          <St.MedleyContainer isClicked={isModalOpen}>
`<St.MedleyContainer>` 도 없어도 될 것 같은데?

2023-03-09 01:27 UTC, joohaem commented on src/@components/MainPage/Medley/MedleyPreview/index.tsx
> +}
❗ 질문1

프리뷰 컴포넌트게서 메들리리스트의 정보가 모두 필요한가요?
아니면 한 메들리의 프리뷰 정보가 필요한가요??

1. 카드의 인덱스가 필요함 -> `medleyIdx: number;`
2. 특정 메들리의 프리뷰 정보가 필요함 -> `{...previewCards}` 를 prop으로 받음. `_id: string, content: string`
3. 특정 메들리의 정보도 필요 -> `title: string, ...`

이것들을 다 props 로 받아주면 될 것 같고-

2023-03-09 01:27 UTC, joohaem commented on src/@components/MainPage/Medley/MedleyPreview/index.tsx
> +      <St.Container ref={outClickCloserRef}>
`Modal` 공통 컴포넌트 사용해주세요!

2023-03-09 01:27 UTC, joohaem commented on src/@components/MainPage/Medley/MedleyPreview/index.tsx
> +      <St.Container ref={outClickCloserRef}>
그리고 메뉴바처럼 애니메이션이 추가되면 좋을 것 같아

2023-03-09 01:27 UTC, joohaem commented on src/@components/MainPage/Medley/index.tsx
> +              })}
❗ 질문1

`{isModalOpen && <MedleyPreview closePreview={toggleModal} />}` 를 이 안에 넣어줘야겠지?

return 안의 요소들을 `MedleyCard` 로 따로 빼내고,
그 안에서 useModal 훅을 사용해서 각 카드에 독립적인 모달을 만들어주면 될 것 같은데!

어떤 에러가 나는지 잘 모르겠어. 자세히 설명해줄래?

2023-03-09 15:33 UTC, NYeonK commented on src/@components/MainPage/Medley/index.tsx
> +
하잇!

2023-03-09 15:36 UTC, NYeonK commented on src/@components/MainPage/Medley/index.tsx
> +          <St.MedleyContainer isClicked={isModalOpen}>
`{isModalOpen && <MedleyPreview closePreview={toggleModal} />}` 요게 안먹어서 `</St.MedleyContainer>`를 만들었는데 오빠 리뷰보니까ㅏ 해볼 수 있을 것 같다!!! 지울게용😋😋

2023-03-09 15:41 UTC, NYeonK commented on src/@components/MainPage/Medley/MedleyPreview/index.tsx
> +      <St.Container ref={outClickCloserRef}>
`Modal`이 있었네 맞네ㅎㅎ 바루 반영할게요!

2023-03-09 15:43 UTC, NYeonK commented on src/@components/MainPage/Medley/index.tsx
> +              })}
웅 거마워:D 오빠가 말한대러 다시 해볼게!! 왜 빼낼 생각을 안했으까😂😂

2023-03-09 19:36 UTC, NYeonK commented
쟘만쟘만~!~!! 물어보고 싶은 것들이 있는데, 오늘 오전 안에 작성할게요!-!

2023-03-10 02:41 UTC, NYeonK commented on src/@components/MainPage/Medley/MedleyPreview/index.tsx
> +}
`Medley` 안에 `MedleyPreiveiw`와 `MedleyCard` 폴더를 만들었는데요!
`MedleyPreiveiw`는 `MedleyCard`에서 사용합니당. 

그래서 `Medley`에서 api 연결하구 props 전달해주려고 하는데,
`MedleyCard`에서는 preview 정보가 필요없거든요! 그래도 props로 전부 받아서 넘겨줘야 할까요?-?

`MedleyPreiveiw`에서 api 한 번 더 쓰는 방법이 더 나을지 궁금합니다.!

2023-03-10 02:48 UTC, joohaem commented on src/@components/MainPage/Medley/MedleyPreview/index.tsx
> +}
api 통신을 한 번 더 하는 건 정말 불필요한 작업같고,

부분 전역적으로 사용하는 context를 사용할 수도 있겠지만
뎁스가 길지도 않아서, prop drilling 하는 게 나아보여요-

2023-03-10 02:49 UTC, joohaem commented
1. 스크린샷 보고는 알 수 없어요... 트러블 슈팅을 하고 어느 부분에서 문제가 생기는 것 같은데, 왜 이렇게 될까요? 정도로 질문해주시면 제가 좀 편할 것 같습니다,,
2. 네! 추가해주세요

2023-03-10 02:57 UTC, NYeonK commented on src/@components/MainPage/Medley/MedleyPreview/index.tsx
> +}
네엡 감사합니당:D

2023-03-10 03:04 UTC, NYeonK commented
아하 한 번 더 확인하고 다시 질문해보겠습니다! 알려주셔서 감사해요 (｡˃́⌔˂̀｡)

카드 주제 제목들은 줄바꿈 요청한 게 아직 반영이 안 돼서, 이후에 확인해보겠습니다!!

2023-03-12 12:39 UTC, joohaem commented
`남은 것`
1. props drilling 해서 프리뷰 컴포넌트 `금방`
2. 서버 데이터 (줄바꿈 등) 적용 `확인`
3. Modal 손보기 + 애니메이션 `해봐야 앎`

2023-03-12 12:44 UTC, merged