Feat/#261 card swiper
TeamPiickle/client pull request #263
Opened 2023-04-12 08:19 UTC by NYeonK

- [x] 브랜치명, 브랜치 알맞게 설정
- [x] Reviewer, Assignees, Label, Milestone, Issue(PR 작성 후에) 붙이기
- [ ] PR이 승인된 경우 해당 브랜치는 삭제하기

## 📌 내용

- 

<br />

## 📌 내가 알게 된 부분

- 

<br />

## 📌 질문할 부분 

- 

<br />

## 📸 스크린샷

<img src="" width=80% />

2023-04-16 14:53 UTC, joohaem requested changes
완전 잘 동작하네요🔥 👍 👍 👍 

리뷰 남겨놓았습니다!!

2023-04-16 14:53 UTC, joohaem commented on src/asset/icon/emptyBookmark.svg
> +<path class="click_card_like" d="M42.9387 10.1915C42.9387 9.56439 42.9387 9.25081 42.8166 9.01127C42.7093 8.80056 42.538 8.62925 42.3272 8.52189C42.0877 8.39984 41.7741 8.39984 41.147 8.39984H14.3952
🚨P1🚨

![image](https://user-images.githubusercontent.com/47105088/232319586-938dae42-2139-476e-81d1-517134c2bcc4.png)

해당 영역을 클릭 해도, 동작하는데, 그렇게 되면 svg 가 클릭 이벤트의 타겟이 되어 GA에 감지가 안 될 것 같아요!
아래처럼 수정이 필요할 것 같습니닷

```suggestion
<svg class="click_card_like" width="56" height="56" viewBox="0 0 56 56" fill="none" xmlns="http://www.w3.org/2000/svg">
<g filter="url(#filter0_i_2355_6996)">
<path class="click_card_like" d="M42.9387 10.1915C42.9387 9.56439 42.9387 9.25081 42.8166 9.01127C42.7093 8.80056 42.538 8.62925 42.3272 8.52189C42.0877 8.39984 41.7741 8.39984 41.147 8.39984H14.3952C13.7681 8.39984 13.4545 8.39984 13.2149 8.52189C13.0042 8.62925 12.8329 8.80056 12.7256 9.01127C12.6035 9.25081 12.6035 9.56439 12.6035 10.1915V44.685C12.6035 45.5922 12.6035 46.0459 12.7945 46.3295C12.9615 46.5774 13.2206 46.7483 13.5142 46.8041C13.8502 46.8679 14.2671 46.6892 15.101 46.3318L27.0653 41.2043C27.3255 41.0928 27.4556 41.037 27.5905 41.015C27.7101 40.9954 27.8321 40.9954 27.9517 41.015C28.0866 41.037 28.2167 41.0928 28.4769 41.2043L40.4412 46.3318C41.2751 46.6892 41.692 46.8679 42.0279 46.8041C42.3216 46.7483 42.5807 46.5774 42.7477 46.3295C42.9387 46.0459 42.9387 45.5922 42.9387 44.685V10.1915Z" fill="#E0E0E0"/>
```

2023-04-16 14:53 UTC, joohaem commented on src/@components/CardCollectionPage/Card/index.tsx
> +      </St.BookmarkWrapper>
svg 파일 하나로, 색깔만 달리 하는 게 어떨까요?? 에셋 하나라도 줄이고자!

2023-04-16 14:53 UTC, joohaem commented on src/@components/MainPage/Banner/index.tsx
>    };
(와우 타입까지 제공하는군요 !)

해당 정적 객체 파일 분리하는 게 어떨까요??

2023-04-16 14:53 UTC, joohaem commented on src/@components/MainPage/Banner/index.tsx
>    };
이전에는 `setCurrentSlide` 때문에 컴포넌트 내에서 선언했는데, 이제 그럴 필요 없어보여요!

2023-04-16 14:53 UTC, joohaem commented on src/@components/CardCollectionPage/style.ts
> +
10단위로 통일함이 어떨까!?
```suggestion
  z-index: 10;

```

2023-04-16 14:53 UTC, joohaem commented on src/@components/@common/Header/HeaderMinVer/style.ts
> +  z-index: 10;
엇 여기는 불필요해 보이는데??!

2023-04-16 14:53 UTC, joohaem commented on src/@components/CardCollectionPage/CardSlider/index.tsx
> +};
해당 설정 객체도 분리하면 좋을 것 같아요!

2023-04-16 14:53 UTC, joohaem commented on src/@components/CardCollectionPage/CardSlider/index.tsx
>          ref={sliderRef}>
해당 설정들 settings에 포함할 수 있지 않을까요??
설정들을 다 명시하는 게 읽는 데에 병목을 만들 수 있을 것 같아요

2023-04-16 14:53 UTC, joohaem commented on src/@components/CardCollectionPage/CardSlider/index.tsx
>          ))}
- `cardList` -> `cardInfo`  는 어떤가요??

(마음같아서는 `cardLists` 도 다 `cardInfos` 로 바꾸고 싶은데, 공수가 커보이네요 :: ))

2023-04-16 14:53 UTC, joohaem commented on src/@components/CardCollectionPage/Card/LastCard/index.tsx
> +      <CategoryContents />
두 병렬적인 섹션이, 같은 위계에 위치해야 읽는 데에 편해요
`<St.ContentWrapper>~</St.ContentWrapper>`  를 따로 컴포넌트로 분리해도 괜찮다고 생각이 들어요!

2023-04-16 14:53 UTC, joohaem commented on src/@components/CardCollectionPage/Card/index.tsx
>          setIsBookmarked((prev) => !prev);
해당 비즈니스 로직 + 위에 `LOGIN_STATE` 와 state 까지 커스텀 훅으로 분리하면 좋을 것 같습니닷

2023-04-17 17:12 UTC, NYeonK commented on src/@components/CardCollectionPage/Card/index.tsx
> +      </St.BookmarkWrapper>
우왓 오빠가 했던 거 적용할랬눈데 까먹었다! 바로 반영할게요😋

2023-04-17 17:13 UTC, NYeonK commented on src/@components/MainPage/Banner/index.tsx
>    };
오홍 좋은데여?!! 분리하겠습니다:)

2023-04-17 17:13 UTC, NYeonK commented on src/@components/CardCollectionPage/style.ts
> +
예리했다!!!!!!!!

2023-04-17 17:14 UTC, NYeonK commented on src/@components/@common/Header/HeaderMinVer/style.ts
> +  z-index: 10;
저도 그런줄 알았는데, 헤더의 버튼들이 안눌리더라구요!

2023-04-17 17:18 UTC, NYeonK commented on src/@components/CardCollectionPage/CardSlider/index.tsx
>          ref={sliderRef}>
```typeScript
direction={"vertical"}
modules={[Pagination]}
```
요 두개 더 이동가능하네욤~.~ 나머지 설정은 `setSliderIdx` 때문에 어려울 것 같아요!

2023-04-17 17:21 UTC, NYeonK commented on src/@components/CardCollectionPage/Card/LastCard/index.tsx
> +      <CategoryContents />
> 두 병렬적인 섹션이, 같은 위계에 위치해야 읽는 데에 편해요

좋은 생각이네요💡💡 
그런데 컴포넌트를 분리하기엔 `ContentWrapper`가 padding 값 설정밖에 안해서 없애는 방향으로 반영해보겠습니다:)

2023-04-17 17:41 UTC, NYeonK commented on src/@components/CardCollectionPage/Card/index.tsx
>          setIsBookmarked((prev) => !prev);
case가 false일 경우에, props로 받아오는 `openLoginModalHandler()`를 사용하는데요! 
`openLoginModalHandler()`는 훅으로 분리를 못하니까,  요 index.tsx에서 조건문을 한 번 더 사용해줘야 할까요?! 그럼 분리하는 의미가 있을지 궁금합니다 (분리하눈 방법이 있다면 알려주세효😚)

2023-04-18 01:04 UTC, joohaem commented on src/@components/@common/Header/HeaderMinVer/style.ts
> +  z-index: 10;
꼼꼼이!

2023-04-18 01:31 UTC, joohaem requested changes

2023-04-18 01:31 UTC, joohaem commented on src/@components/CardCollectionPage/CardSlider/index.tsx
> +        ref={swiperRef}>
className은 우리가 추가한 prop이지만
initialSlide, onSlideChange는 Swiper에서 제공하는 prop이기 때문에 함께 분리하는 게 좋아보여요

```suggestion
      <Swiper
        className="swiper"
        {...swiperSettings}>
```

2023-04-18 01:31 UTC, joohaem commented on src/@components/CardCollectionPage/CardSlider/index.tsx
> +  const swiperRef = useRef<SwiperRef | null>(null);
요 ref의 용도는 뭔가요??! 제거해도 되려나 싶네요!

2023-04-18 01:31 UTC, joohaem commented on src/@components/CardCollectionPage/CardSlider/index.tsx
> +        ref={swiperRef}>
그래서 `useRecoilState(sliderIdxState)` 까지 `useCardSwiper` 훅으로 분리함으로써

1. 컨포넌트 단에서는 UI 정보만 받아 UI를 보여주는 역할만 하게 되고,
2. 커스턴 훅 에서는 스와이퍼 정보들을 가공하고 `swiperSettings`만 내뱉는 역할을 해주는 거죠- 그렇게 되면 다른 컴포넌트에서도 재사용이 가능할 거구요

2023-04-18 01:31 UTC, joohaem commented on src/@components/MainPage/Banner/index.tsx
> +        <Swiper {...swiperSettings} onSlideChange={(swiper) => setCurrentSlide(swiper.realIndex)}>
요놈도 마찬가지로, `onSlideChange`, `currentSlider` 까지 훅으로 분리함이 좋아보입니다

`useBannerSwiper`는 `{ swiperSettings, currentSlide }` 만 주면 되겠네요

2023-04-18 01:31 UTC, joohaem commented on src/@components/MainPage/hooks/useBannerSwiper.ts
> +}
이건 커스텀 훅이 되지 않아요0 그냥 객체일 뿐이에요.

```suggestion
export const swiperSettings: SwiperOptions = {
  slidesPerView: 1,
  loop: true,
};
```

Hook은 useState, useEffect와 같이 라이프사이클에 기반하여 React 내부에서 감지되고, 동작해요.
그래서 Custom Hook은 이런 `use~` 가 내부에 있을 때 구성하는 훅이에요

(useState를 내부에 넣고 함수명을 `bannerSwiper`로 지었다? 하면 lint에서 에러가 나요. `use~` 접두어를 붙여줘! 하고요)

지금은 어차피 state나 recoilState를 넣을 것이니 커스텀 훅은 그대로 놓아도 괜찮습니다!

2023-04-18 01:43 UTC, joohaem commented on src/@components/CardCollectionPage/Card/index.tsx
>          setIsBookmarked((prev) => !prev);
https://github.com/TeamPiickle/client/pull/263/commits/5a74ee1db110d9ae0208d25950e02a9f3c3c7cfc

해당 commit 확인해보고, 피드백 주세요!!

2023-04-19 04:49 UTC, NYeonK commented on src/@components/CardCollectionPage/CardSlider/index.tsx
> +        ref={swiperRef}>
아하 `useRecoilState(sliderIdxState)`까지 분리하는 방법이 있군요👀👀 해보겠습니다:)

2023-04-19 04:50 UTC, NYeonK commented on src/@components/CardCollectionPage/CardSlider/index.tsx
> +  const swiperRef = useRef<SwiperRef | null>(null);
원래 slider에 있던거라, type만 바꿔서 그대로 적용했어요😋

2023-04-19 04:51 UTC, NYeonK commented on src/@components/MainPage/hooks/useBannerSwiper.ts
> +}
오오오오옷 이해했습니다😆👍 친절한 설명 감사합니당🌸🌸

2023-04-19 04:53 UTC, NYeonK commented on src/@components/CardCollectionPage/Card/index.tsx
> +  const { isBookmarked, handleClickBookmark } = useCardBookmark(isBookmark, openLoginModalHandler);
오빤 천재야🙉🌟👑

2023-04-19 05:04 UTC, joohaem commented on src/@components/CardCollectionPage/CardSlider/index.tsx
> +  const swiperRef = useRef<SwiperRef | null>(null);
@NYeonK ref 없어도 되지 않나요?

2023-04-19 06:42 UTC, joohaem approved these changes

2023-04-19 06:42 UTC, merged